name: EarlyWarning

on: 
    schedule:
     - cron: '25 0/1 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SetUp Python
        uses: actions/setup-python@v2
      - name: Install Package
        run: |
          pip install requests
      - name: Run Python Script
        run: |
          python EarlyWarning.py ${{secrets.EMAIL_ADDRESS}} ${{secrets.EMAIL_PASSWORD}} ${{secrets.WEATHER_API}} ${{secrets.AQI_API}} ${{secrets.WEATHER_PRE}} 
