name: EarlyWarning

on: 
    push:
    schedule:
     - cron: '45 0/1 * * *'


jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#使用自己的服务器就不需 要装环境了 
#      - name: SetUp Python
#        uses: actions/setup-python@v2
#      - name: Install Package
#        run: |
#          pip install requests
      - name: Run Python Script
        run: |
          python3 EarlyWarning.py ${{secrets.EMAIL_ADDRESS}} ${{secrets.EMAIL_PASSWORD}} ${{secrets.WEATHER_API}} ${{secrets.AQI_API}} ${{secrets.WEATHER_PRE}} ${{secrets.AUTHORIZATION_API}} ${{secrets.HYDRAULIC_REALTIME}} ${{secrets.HYDRAULIC_DAY}} ${{secrets.HYDRAULIC_HOUR}} 
